/* Generated by ./xlat/gen.sh from ./xlat/mremap_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"


#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat mremap_flags in mpers mode

# else

static const struct xlat_data mremap_flags_xdata[] = {
#if defined(MREMAP_MAYMOVE) || (defined(HAVE_DECL_MREMAP_MAYMOVE) && HAVE_DECL_MREMAP_MAYMOVE)
  XLAT(MREMAP_MAYMOVE),
 #define XLAT_VAL_0 ((unsigned) (MREMAP_MAYMOVE))
 #define XLAT_STR_0 STRINGIFY(MREMAP_MAYMOVE)
#endif
#if defined(MREMAP_FIXED) || (defined(HAVE_DECL_MREMAP_FIXED) && HAVE_DECL_MREMAP_FIXED)
  XLAT(MREMAP_FIXED),
 #define XLAT_VAL_1 ((unsigned) (MREMAP_FIXED))
 #define XLAT_STR_1 STRINGIFY(MREMAP_FIXED)
#endif
};
static
const struct xlat mremap_flags[1] = { {
 .data = mremap_flags_xdata,
 .size = ARRAY_SIZE(mremap_flags_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
  ,
} };

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
